---
- name: Reload systemd configuration
  service:
    daemon_reload: True

- name: Restart systemd-networkd
  service:
    name: systemd-networkd
    enabled: True
    state: restarted

- name: Disable unwanted resolvers
  service:
    name: "{{ item }}"
    enabled: False
    state: stopped
  loop: "{{ _systemd_network_resolv_conf_paths.keys() | difference([systemd_network_dns_resolver]) }}"
  listen: Configure resolver

- name: Enable wanted resolver
  service:
    name: "{{ systemd_network_dns_resolver }}"
    enabled: True
    state: started
  listen: Configure resolver
